"""Deterministic human-readable projection of all catalogue decisions and mappings."""
import hashlib
import json


def cell(value):
    return str(value).replace('|', '\\|').replace('\n', ' ')


def ids(values):
    return ', '.join('`' + value + '`' for value in values) or 'None'


def render_matrix(catalogue):
    digest = hashlib.sha256(json.dumps(catalogue, sort_keys=True, separators=(',', ':')).encode()).hexdigest()
    out = [
        '# Linux capability matrix', '',
        'Generated by `python3 -B script/render-matrix --write` from',
        '`catalogue/capabilities.json`. Run `python3 -B script/check-catalogue` to detect drift.', '',
        f'Catalogue revision: `{catalogue["revision"]}`. Canonical content SHA-256: `{digest}`.',
        f'Mac reference: `{catalogue["provenance"]["mac_commit"]}`.', '',
        'KEEP means selected in the personal target, not installed or tested. The reusable',
        'default excludes GPU-profile capabilities. OPTIONAL is disabled; PENDING needs a',
        'decision; OMIT is excluded. Manual entries describe operator work, not automation.', '',
        'Delivery metadata and pre-build evidence are independent of selection. Null pins or',
        'unresolved source checks are never trusted defaults. See [architecture](ARCHITECTURE.md)',
        'and [source review](SOURCE-REVIEW.md) for remaining gates.', '',
    ]
    for decision in ('keep', 'optional', 'pending', 'omit'):
        out += ['## ' + decision.upper(), '', '| ID | Purpose | Profile / owner |', '|---|---|---|']
        for entry in sorted(catalogue['capabilities'], key=lambda e: e['id']):
            if entry['decision'] == decision:
                out.append(f'| `{entry["id"]}` | {cell(entry["purpose"])} | {cell(entry["profile"])} / {cell(entry["owner"])} |')
        out += ['']
    out += ['## Linux review coverage', '', 'Source: [preserved review](software-review.md). Later decisions supersede raw notes.', '', '| Row | Observed group | Raw decision | Capability IDs |', '|---|---|---|---|']
    for row in catalogue['linux_review_rows']:
        out.append(f'| {row["id"]} | {cell(row["label"])} | {cell(row["raw_decision"])} | {ids(row["capability_ids"])} |')
    out += ['', '## Linux extension families', '', '| Family | Selected root | Treatment |', '|---|---|---|']
    for row in catalogue['linux_extension_families']:
        out.append(f'| {cell(row["family"])} | {ids(row["capability_ids"])} | {cell(row["note"])} |')
    out += ['', '## Mac profile coverage', '', 'Mac-only tokens are provenance, not installable Linux entries. Commented declarations', 'are evidence of options, not default selection.', '', '| Source | Token | Mac declaration | Disposition | Linux capabilities | Treatment |', '|---|---|---|---|---|---|']
    for row in catalogue['mac_profile_mappings']:
        out.append(f'| `{row["source"]}:{row["line"]}` | {cell(row["token"])} | ' + ('active' if row['active_in_mac_profile'] else 'commented') + f' | {cell(row["disposition"])} | {ids(row["capability_ids"])} | {cell(row["note"] or "")} |')
    out += ['', '## Mac extension coverage', '', 'Historical Mac versions are not Linux release pins.', '', '| Source | Root | Mac declaration | Linux capabilities |', '|---|---|---|---|']
    for row in catalogue['mac_extension_mappings']:
        out.append(f'| `{row["source"]}:{row["line"]}` | {cell(row["identifier"])} | ' + ('active' if row['active_in_mac_manifest'] else 'commented') + f' | {ids(row["capability_ids"])} |')
    out += ['', '## Configuration and helper coverage', '', 'Port behavior; never execute these Mac source paths from Linux.', '', '| Mac source | Linux capabilities | Treatment |', '|---|---|---|']
    for row in catalogue['mac_source_mappings']:
        out.append(f'| `{row["source"]}` | {ids(row["capability_ids"])} | {cell(row["note"])} |')
    return '\n'.join(out) + '\n'
